# Generated by Django 4.0.2 on 2022-03-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartDevice',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('color', models.TextField()),
                ('material', models.TextField()),
                ('CPU', models.TextField()),
                ('GPU', models.TextField()),
                ('OS', models.TextField()),
                ('screenSize', models.FloatField()),
                ('storage', models.TextField()),
                ('battery', models.TextField()),
                ('weight', models.FloatField()),
                ('warrantyPeriod', models.TextField()),
                ('speaker', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SmartDeviceBrand',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('createAt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('smartdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smartdivice.smartdevice')),
                ('type', models.TextField()),
                ('webCam', models.TextField()),
                ('keyborad', models.TextField()),
            ],
            bases=('smartdivice.smartdevice', models.Model),
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('smartdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smartdivice.smartdevice')),
                ('touchID', models.TextField()),
                ('sims', models.TextField()),
                ('frontCamera', models.TextField()),
                ('rearCamera', models.TextField()),
            ],
            bases=('smartdivice.smartdevice', models.Model),
        ),
        migrations.CreateModel(
            name='SmartDeviceStats',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('importPrice', models.FloatField()),
                ('quantityLeft', models.IntegerField()),
                ('createAt', models.DateField()),
                ('smartDevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartdivice.smartdevice')),
            ],
        ),
        migrations.CreateModel(
            name='SmartDeviceItem',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.TextField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('smartDevice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartdivice.smartdevice')),
            ],
        ),
        migrations.AddField(
            model_name='smartdevice',
            name='smartDeviceBrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartdivice.smartdevicebrand'),
        ),
    ]
