# Generated by Django 4.0.2 on 2022-03-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='color',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='gender',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='material',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='name',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='season',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.TextField(max_length=255),
        ),
    ]
