# Generated by Django 4.0.2 on 2022-03-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_clothes_color_alter_clothes_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='ID',
            field=models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clothesbrand',
            name='ID',
            field=models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clothesitem',
            name='ID',
            field=models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clothesstats',
            name='ID',
            field=models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False),
        ),
    ]
