# Generated by Django 4.0.2 on 2022-03-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_clothes_id_alter_clothesbrand_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesstats',
            name='barcode',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothes',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clothesbrand',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clothesitem',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clothesstats',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
